# Generated by Django 2.2.12 on 2020-05-29 14:11

from django.db import migrations, models
import taggit.managers
import website.models


class Migration(migrations.Migration):

    dependencies = [
        ('icon_color_tags', '0001_initial'),
        ('website', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='MachineLearning',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=50)),
                ('desc', models.CharField(blank=True, max_length=500)),
                ('fromdate', models.DateField()),
                ('todate', models.CharField(blank=True, max_length=500)),
                ('project_link', models.CharField(blank=True, max_length=500)),
                ('image', models.ImageField(blank=True, null=True, upload_to=website.models.get_upload_path)),
                ('video', models.FileField(blank=True, null=True, upload_to=website.models.get_upload_path, verbose_name='')),
                ('tags', taggit.managers.TaggableManager(help_text='A comma-separated list of tags.', through='icon_color_tags.TaggedThing', to='icon_color_tags.IconColorTag', verbose_name='Tags')),
            ],
        ),
    ]
