# Generated by Django 2.2.12 on 2020-05-29 16:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0002_machinelearning'),
    ]

    operations = [
        migrations.DeleteModel(
            name='MachineLearning',
        ),
    ]
